# Grupo C
# Alunos:
# Gustavo Sleman Lenz - 00290394
# Vinicius Daniel Spadotto - 00341554

./obj/tests: ./src/testing/*.c ./include/testing/*.h ./obj/parser.tab.c ./obj/lex.yy.c
	mkdir -p obj
	gcc ./src/testing/*.c ./src/asd.c ./obj/parser.tab.c ./obj/lex.yy.c -o ./obj/tests -lfl

./obj/parser.tab.c: ./src/parser.y ./obj/
	bison -d ./src/parser.y
	mv ./parser.tab.c ./obj/parser.tab.c
	mv ./parser.tab.h ./obj/parser.tab.h

./obj/lex.yy.c: ./src/scanner.l ./obj/
	flex -o ./obj/lex.yy.c ./src/scanner.l

./obj/:
	mkdir -p obj
